<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.course.cases.GetUserInfoTest" tests="1" time="0.161" ignored="0" failures="1" timestamp="14 五月 2019 03:04:27 GMT" skipped="0" hostname="Ze" errors="0">
  <testcase name="getUserInfo" time="0.161" classname="com.course.cases.GetUserInfoTest">
    <failure type="java.lang.AssertionError" message="expected [{&quot;age&quot;:21,&quot;gender&quot;:&quot;female&quot;,&quot;id&quot;:2,&quot;isDelete&quot;:1,&quot;password&quot;:&quot;111111&quot;,&quot;permission&quot;:1,&quot;userName&quot;:&quot;luffy&quot;}] but found [&quot;[{\&quot;id\&quot;:2,\&quot;userName\&quot;:\&quot;luffy\&quot;,\&quot;password\&quot;:\&quot;111111\&quot;,\&quot;gender\&quot;:\&quot;female\&quot;,\&quot;age\&quot;:21,\&quot;permission\&quot;:1,\&quot;isDelete\&quot;:1}]&quot;]">
      <![CDATA[java.lang.AssertionError: expected [{"age":21,"gender":"female","id":2,"isDelete":1,"password":"111111","permission":1,"userName":"luffy"}] but found ["[{\"id\":2,\"userName\":\"luffy\",\"password\":\"111111\",\"gender\":\"female\",\"age\":21,\"permission\":1,\"isDelete\":1}]"]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.course.cases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.course.RunTestNGXml.main(RunTestNGXml.java:14)
]]>
    </failure>
  </testcase> <!-- getUserInfo -->
</testsuite> <!-- com.course.cases.GetUserInfoTest -->
